"""empty message

Revision ID: 2a9e17ed8890
Revises: 
Create Date: 2024-09-01 16:16:10.685327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9e17ed8890'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('whatsapp', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('cidade', sa.String(length=150), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cep')
    )
    op.create_table('credor',
    sa.Column('cnpj', sa.String(length=13), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('ender_cep', sa.String(length=8), nullable=True),
    sa.Column('contato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['contato.id'], ),
    sa.ForeignKeyConstraint(['ender_cep'], ['endereco.cep'], ),
    sa.PrimaryKeyConstraint('cnpj')
    )
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=True),
    sa.Column('credor_cnpj', sa.String(length=13), nullable=True),
    sa.Column('valor', sa.Double(), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['credor_cnpj'], ['credor.cnpj'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta')
    op.drop_table('credor')
    op.drop_table('endereco')
    op.drop_table('contato')
    # ### end Alembic commands ###
