"""empty message

Revision ID: a8a3ecbcc26d
Revises: 2a9e17ed8890
Create Date: 2024-09-01 16:22:15.712401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a3ecbcc26d'
down_revision = '2a9e17ed8890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.alter_column('credor_cnpj',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=14),
               existing_nullable=True)

    with op.batch_alter_table('credor', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credor', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)

    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.alter_column('credor_cnpj',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)

    # ### end Alembic commands ###
